# Generated by Django 5.2.8 on 2026-01-25 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="items",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
    ]
