# Generated by Django 5.2.8 on 2025-12-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0015_pagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('preparing', 'Em Separação'), ('shipping', 'Em Rota'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_note', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='Base_App.order')),
            ],
        ),
    ]
