# Generated by Django 5.2.8 on 2025-12-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0016_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
