# Generated by Django 5.2.8 on 2025-12-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0017_deliveryperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='Base_App.deliveryperson'),
        ),
    ]
