# Generated by Django 5.2.8 on 2025-12-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0018_alter_delivery_delivery_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
